apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scc
  namespace: default
spec:
  destination:
    namespace: default
    server: https://api.ocp.chris.domain:6443
  project: default
  source:
    path: cluster/
    repoURL: https://github.com/Markieta/argocd-openshift-demo
    targetRevision: master